# Generated by Django 3.2.11 on 2022-01-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movetype',
            name='score',
        ),
        migrations.AlterField(
            model_name='movetype',
            name='name',
            field=models.CharField(blank=True, choices=[('rock', 'rock'), ('paper', 'paper'), ('scissor', 'scissor')], max_length=30, null=True),
        ),
    ]
