# Generated by Django 3.2.11 on 2022-01-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_auto_20220112_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelog',
            name='log_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
