# Generated by Django 3.2.11 on 2022-01-13 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playground', '0005_alter_move_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='against',
            field=models.ForeignKey(default=25, on_delete=django.db.models.deletion.CASCADE, related_name='bot_moves', to='accounts.user'),
            preserve_default=False,
        ),
    ]
